### ISSUE TITLE
你好，这种报错是正常的吗(

### ISSUE THREAD

**Issue by damemod** [MistEO/Pallas-Bot#32]
![image](https://user-images.githubusercontent.com/85817502/180781051-a1636bb6-0090-4f36-a340-67fd62e63712.png)
![image](https://user-images.githubusercontent.com/85817502/180781102-8ef89baf-e5e4-4c12-960e-5326e77f7b1f.png)
n

**Comment by damemod** [comment]
很抱歉的是，我不知道该提供什么07-25 21:34:23 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.repeater, type=message, priority=5, temp=False>.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\message.py", line 130, in _check_matcher
    if not await Matcher.check_perm(
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\internal\matcher.py", line 269, in check_perm
    return event_type == (cls.type or event_type) and await cls.permission(
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\internal\permission.py", line 67, in __call__
    results = await asyncio.gather(
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\utils.py", line 138, in run_coro_with_catch
    return await coro
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\permission.py", line 83, in __call__
    f"{bot.adapter.get_name().split(maxsplit=1)[0].lower()}:{event.get_user_id()}"
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 54, in get_user_id
    raise ValueError("Event has no context!")
ValueError: Event has no context!
07-25 21:34:23 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.repeater, type=message, priority=5, temp=False>.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\message.py", line 130, in _check_matcher
    if not await Matcher.check_perm(
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\internal\matcher.py", line 269, in check_perm
    return event_type == (cls.type or event_type) and await cls.permission(
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\internal\permission.py", line 67, in __call__
    results = await asyncio.gather(
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\utils.py", line 138, in run_coro_with_catch
    return await coro
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\permission.py", line 83, in __call__
    f"{bot.adapter.get_name().split(maxsplit=1)[0].lower()}:{event.get_user_id()}"
  File "c:\evm\bot\niuniu\niuniu\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 54, in get_user_id
    raise ValueError("Event has no context!")
ValueError: Event has no context!

**Comment by damemod** [comment]
但是很抱歉我不知道该如何描述
当nb cil时会替换掉requests的版本，(现已不报错)当python pip install -r requirements也会替换requests并且报错，有时附带ValueError("'tool' in toml file is not a Table!")的提示
![image](https://user-images.githubusercontent.com/85817502/180790446-112d00e4-14af-41ce-bc06-957f9c223109.png)
而一切安装好时牛牛依旧有回复，我猜测可能是频道的回复有问题?
[err.txt](https://github.com/MistEO/Pallas-Bot/files/9181611/err.txt)

**Comment by damemod** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
